=== svenkeidel/tierquiz/frontend/old/src/animals-schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#", 
  "type": "array",
  "format": "table",
  "items": {
    "title": "Tier", 
    "type": "object",
    "properties": {
      "species": {
        "title": "Spezies", 
        "description": "Liste von Tier namen. Namen werden von rechts nach links aus dem Text enfernt.", 
        "type": "array",
        "items": {"type": "string"}
      }, 
      "image": {
        "title": "Bild", 
        "description": "URL zu einem Bild des Tieres.", 
        "type": "string"
      }, 
      "taxonomy": {
        "title": "Systematik", 
        "type": "object",
        "properties": {
          "order": {
            "title": "Ordnung", 
            "type": "string"
          },
          "family": {
            "title": "Familie", 
            "type": "string"
          } 
        } 
      },
      "characteristic":  {"title": "Aussehen", "type": "string"}, 
      "distribution":    {"title": "Verbreitung", "type": "string"}, 
      "habitat":         {"title": "Lebensraum", "type": "string"}, 
      "behavior":        {"title": "Verhalten", "type": "string"}, 
      "diet":            {"title": "Ern√§hrung", "type": "string"}, 
      "reproduction":    {"title": "Vermehrung", "type": "string"}, 
      "socialStructure": {"title": "Sozialverhalten", "type": "string"}
    }
  }
}

=== svenkeidel/tierquiz/animals.json
[
    {
        "species": [ "Gibbon", "Gibbons" ],
        "image":"https://upload.wikimedia.org/wikipedia/commons/6/66/Weisshandgibbon_tierpark_berlin.jpg",
        "taxonomy": {
            "order":"Primaten",
            "family":"Gibbons"
        },
        "distribution":"Gibbons kommen in Südostasien vor, ihr Verbreitungsgebiet erstreckt sich von Nordostindien, Myanmar und Südchina über Indochina und die Malaiische Halbinsel bis zu den indonesischen Inseln Borneo und Java. In früheren Zeiten waren Gibbons weiter verbreitet, noch in der ersten Hälfte des 2. Jahrtausends fand man sie beispielsweise in einem Großteil Chinas.",
        "habitat":"Ihr Verbreitungsgebiet sind in erster Linie Regenwälder, manchmal kommen sie auch in Gebirgswäldern bis 1800 m Höhe vor.",
        "behavior":"Gibbons sind tagaktive Waldbewohner, die mit ihren langen Armen und den weit unten ansetzenden Daumen perfekt an die hangelnde Lebensweise angepasst sind. Sie schwingen durch die Bäume und können mit einem einzigen Schwung 3 m zurücklegen. Auf dem Boden bewegen sie sich zweibeinig voran (Bipedie), wobei sie die Arme aus Balancegründen hoch in die Luft strecken.",
        "characteristic":"Gibbons sind schwanzlose Primaten. Auffallend ist, dass die vorderen Gliedmaßen wesentlich länger als die hinteren sind. Dieses ermöglicht ihnen die im Tierreich einmalige Fortbewegungsform des Schwinghangelns (Brachiation). Ihr Daumen wurzelt nahe dem Handgelenk und ermöglicht so einen sicheren Griff um die Äste. Ihr dichtes Fell ist schwarz, grau oder braun gefärbt, ihre Schnauzen sind kurz und die großen Augen nach vorn gerichtet. Die Zahnformel entspricht mit 2-1-2-3 der der Menschenaffen. Einige Arten haben einen Kehlsack, der ihnen als Resonanzkörper beim Ausstoßen ihrer lauten Schreie dient. Gibbons erreichen eine Kopfrumpflänge von 45 bis 90 cm und ein Gewicht von 4 bis 13 kg, wobei der Siamang bei weitem die größte und schwerste Art darstellt.",
        "reproduction":"Es dürfte bei den Gibbons keine feste Paarungssaison geben. Alle zwei bis drei Jahre bringt das Weibchen ein einzelnes Jungtier zur Welt, Zwillingsgeburten sind selten. Das Neugeborene klammert sich als aktiver Tragling zunächst an den Bauch der Mutter, später beteiligt sich auch der Vater an dessen Aufzucht. Vollständig entwöhnt sind junge Gibbons erst mit eineinhalb bis zwei Jahren und die Geschlechtsreife tritt mit acht bis neun Jahren ein. Ihre Lebenserwartung in freier Wildbahn dürfte rund 25 Jahre betragen.",
        "diet":"Gibbons ernähren sich vorwiegend von Pflanzen und nehmen nur selten fleischliche Nahrung zu sich. Früchte machen 44 bis 72 % (im Mittel 65 %) der Nahrung aus, Blätter 3 bis 45 % (im Mittel 30 %). Tierische Nahrung macht im Mittel nur einen sehr geringen Anteil aus (0 bis 25 %).\nDa ihre Hauptnahrung, Früchte, in verschiedenen Jahreszeiten reifen, können Gibbons diese Nahrung im ganzen Jahreszyklus auffinden und verwerten. Meist fressen sie reifes Obst. Gibbons wenden täglich rund 9 bis 10 Stunden für die Nahrungssuche auf. Entsprechend dem Blattanteil im Nahrungsspektrum der betreffenden Art sind die Backenzähne mehr oder weniger großflächig, um diese Nahrung angemessen zu kauen. Der voluminöse Blind- und Grimmdarm mit dem einkammerigen Magen sind in der Lage, den Blattanteil in ihrer Nahrung zu verdauen.\nDurch ihre Nahrungszusammensetzung kommen sie eher mit Vögeln und Eichhörnchen in Konkurrenz als mit anderen Primaten.",
        "socialStructure":"Gibbons leben monogam. Ein Paar und sein Nachwuchs leben in einem Revier, das sie gegen Eindringlinge verteidigen. Gelegentlich findet man auch Einzeltiere, meist junge Erwachsene, die ihre Familie verlassen mussten. Auf der Suche nach einem eigenen Partner verlassen Jungtiere ihre Eltern oder werden von diesen mit Gewalt verjagt. Die Suche nach einem geeigneten Partner kann sich über mehrere Jahre hinziehen. Bei manchen Arten unterstützen die Eltern ihren Nachwuchs, indem sie ein freies Gebiet für ihn „reservieren“.\nGibbons sind streng territorial, das Revier eines Paares ist zwischen 25 und 50 ha groß. Es kommt selten zu Kämpfen mit Eindringlingen, vielmehr versuchen sie, ihr Territorium durch Schreie oder Drohgebärden (Hüpfen oder Abbrechen von Ästen) zu verteidigen. Sie kennen überhaupt ein großes Lautrepertoire, das von den Männchen, manchmal auch im Duett mit Weibchen, vorgetragen wird und verstärkt durch den Kehlsack zu einem eindrucksvollen Konzert wird."
    },
    {
        "species": [ "Gepard", "Geparde" ],
        "image":"https://upload.wikimedia.org/wikipedia/commons/a/a9/Cheetah4.jpg",
        "taxonomy": {
            "order":"Raubtiere",
            "family":"Katzen"
        },
        "distribution":"Der Gepard war einst über fast ganz Afrika mit Ausnahme der zentralafrikanischen Waldgebiete verbreitet; außerdem waren Vorderasien, die indische Halbinsel und Teile Zentralasiens besiedelt. Heute ist er fast nur noch in Afrika südlich der Sahara anzutreffen. In Asien gibt es winzige Restbestände, die am Rande der Ausrottung stehen.",
        "habitat":"Geparde sind reine Savannen- und Steppentiere. Sie bevorzugen Bereiche mit hohem, Deckung bietendem Gras und Hügeln als Ausschaupunkten. Zu viele Bäume und Sträucher machen eine Landschaft für Geparde ungeeignet, da sie dort ihre Schnelligkeit nicht ausnutzen können. In Halbwüsten kommen Geparde dagegen gut zurecht, wenn sie genügend Beutetiere finden.",
        "behavior":"Geparde sind tagaktive Tiere. Dadurch vermeiden sie weitgehend Begegnungen mit den eher nachtaktiven Löwen, Leoparden, Tüpfel-, Streifen- und Schabrackenhyänen, die Geparden leicht die Beute streitig machen können und auch eine große Gefahr für den Nachwuchs darstellen.",
        "characteristic":"Das Gepardfell hat eine goldgelbe Grundfarbe, wobei die Bauchseite meist deutlich heller ist. Es ist mit schwarzen Flecken übersät, die deutlich kleiner sind als die eines Leoparden und keine Rosetten bilden. Das Gesicht ist dunkler und ungefleckt, trägt aber zwei schwarze Streifen, die von den Augen zu den Mundwinkeln laufen (Tränenstreifen).\nIn Bezug auf die Fleckung ähnelt der Gepard zwar dem Leoparden, in seiner Gestalt unterscheidet er sich jedoch beträchtlich von diesem wie auch von allen anderen Katzen. Geparde haben extrem lange, dünne Beine und einen sehr schlanken Körper, der dem eines Windhundes sehr ähnelt. Der Kopf ist klein und rund, der Schwanz lang. Die Pfoten tragen dicke, schuppige Sohlen; die Krallen sind nur bedingt einziehbar (daher der Gattungsname). Aufgrund seines Körperbaus ist der Gepard das schnellste Landtier der Welt. Er erreicht im Lauf bis zu 93 km/h, kann diese hohe Geschwindigkeit aber nur etwa 400 m durchhalten. Die Anatomie des Gepards ist auch in weiteren Punkten auf Schnelligkeit ausgelegt: seine Nasengänge sind erheblich verbreitert, so dass wenig Platz für das Gebiss bleibt, das gegenüber anderen Katzen stark verkleinert und damit eine relativ schwache Waffe ist. Auch Lungen, Bronchien und Nebennieren sind proportional stark vergrößert.\nEin Gepard erreicht eine Kopf-Rumpf-Länge von 150 cm, hinzu kommen 70 cm Schwanz. Die Schulterhöhe beträgt 80 cm. Trotz dieser stattlichen Größe bringt er es nur auf ein Gewicht von 60 kg.",
        "reproduction":"Im Alter von etwa drei Jahren ist ein Gepard geschlechtsreif. Die Tragzeit beträgt etwa 95 Tage, ein Wurf besteht zumeist aus einem bis fünf Jungen. Es kommen aber auch Würfe mit bis zu acht Jungtieren vor. Das Weibchen bringt sie in einem Bau zur Welt, in dem sie für etwa acht Wochen bleiben. Dies ist nötig, da Geparde nicht die körperlichen Voraussetzungen besitzen, ihren Nachwuchs erfolgreich gegen die stärkeren Großkatzen – Löwe und Leopard – oder auch Hyänen zu verteidigen. Die Jungen haben auf dem Rücken lange silbrige Haare, die wahrscheinlich der Tarnung dienen und die sie nach etwa drei Monaten rasch verlieren. Trotz dieser natürlichen Schutzvorrichtungen ist die Mortalität während des ersten Lebensjahres hoch; meistens fallen sie Raubfeinden zum Opfer. Haben sie die erste kritische Phase überstanden, können sie ein Lebensalter von 15 Jahren erreichen.",
